version: '3'

services:
  jupyterhub:
    build: jupyterhub                
    image: iisy/jupyterhub
    container_name: iisy/jupyterhub   
    volumes:                         
      - /var/run/docker.sock:/var/run/docker.sock # Give access to Docker socket.
    ports:
      - "8000:8000" # hub port
    environment:
      # General
      DOCKER_JUPYTER_IMAGE: iisy/jupyterlab
      DOCKER_NETWORK_NAME: jupyterhub-default
      HUB_IP: iisy/jupyterhub
      # OAUTH Settings
      OAUTH_CLIENT_SECRET: ${CLIENT_SECRET}
      OAUTH_CLIENT_ID: ${CLIENT_ID}
      OAUTH_CALLBACK_URL: http://localhost:8000/hub/oauth_callback
      GITLAB_HOST: https://gitlab.beuth-hochschule.de/
      # Nvidia Settings
      CUDA_INSTALLED: "no" # "yes" or "no"
    restart: on-failure
    # TODO: advanced network settings (just local network)

  jupyterlab:
    build: jupyterlab
    image: iisy/jupyterlab
    container_name: iisy/jupyterlab-throwaway
    command: echo